language: ruby
env:
  global:
    - CC_TEST_REPORTER_ID=944f313b82459ad1bfb349d775bfd6adaa8ec256da84357ba1741523e42d0004
rvm:
  - ruby-2.4.2
addons:
  - postgresql: '9.6'
cache: bundler
before_script:
  - psql -c 'create database snuev_backend_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.3.deb
  - sudo dpkg -i --force-confnew elasticsearch-5.6.3.deb
  - sudo service elasticsearch restart
  - sleep 10
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
