language: ruby
env:
  global:
    - CC_TEST_REPORTER_ID=944f313b82459ad1bfb349d775bfd6adaa8ec256da84357ba1741523e42d0004
    - ES_VERSION=6.1.1 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
rvm:
  - ruby-2.4.2
addons:
  - postgresql: '9.6'
cache: bundler
before_script:
  - psql -c 'create database snuev_backend_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch &
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch-plugin install https://oss.sonatype.org/service/local/repositories/releases/content/org/bitbucket/eunjeon/elasticsearch-analysis-seunjeon/6.1.1.1/elasticsearch-analysis-seunjeon-6.1.1.1.zip
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
