version: '3'
services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    ports:
      - '3001:3000'
    links:
      - db
    volumes:
      - .:/usr/src/app
      - bundle:/bundle
    environment:
      - DATABASE_URL=postgres://postgres@db/snuev
      - HTTP_HOST=localhost:3001
      - RAILS_ENV=development
    env_file: .env
  db:
    image: postgres:9.6
    volumes:
      - 'postgres:/var/lib/postgresql/data'
volumes:
  bundle:
  postgres:
