version: '3'
services:
  test:
    build: .
    command: bundle exec rspec
    depends_on:
      - db
      - es
    links:
      - db
      - es
    volumes:
      - '.:/usr/src/app'
      - 'bundle:/bundle'
    environment:
      - RAILS_ENV=test
      - DATABASE_URL=postgres://postgres@db/snuev_test
      - ELASTIC_SEARCH_URL=es:9200
    env_file: .env
  db:
    image: postgres:9.6
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment:
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    volumes:
      - 'esdata:/usr/share/elasticsearch/data'
    ports:
      - '9200:9200'
volumes:
  bundle:
  postgres:
  esdata:
