version: '3'
services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    ports:
      - '3001:3000'
    depends_on:
      - db
      - es
    links:
      - db
      - es
    volumes:
      - '.:/usr/src/app'
      - 'bundle:/bundle'
    environment:
      - DATABASE_URL=postgres://postgres@db/snuev
      - ELASTIC_SEARCH_URL=es:9200
      - HTTP_HOST=localhost:3001
      - RAILS_ENV=development
      - WEB_CONCURRENCY=1
      - RAILS_MAX_THREADS=2
    env_file: .env
  db:
    image: postgres:9.6
    ports:
      - '5433:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  es:
    image: thefron/elasticsearch-seunjeon
    environment:
      - ES_JAVA_OPTS=-Xmx128m -Xms128m
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - xpack.graph.enabled=false
    volumes:
      - 'esdata:/usr/share/elasticsearch/data'
    ports:
      - '9200:9200'
volumes:
  bundle:
  postgres:
  esdata:
